# Generated by Django 4.2.7 on 2025-09-17 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel')),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Mínimo')),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Máximo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('estado_laboral', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'En Licencia'), ('RENUNCIADO', 'Renunciado'), ('DESPEDIDO', 'Despedido')], default='ACTIVO', max_length=20, verbose_name='Estado Laboral')),
                ('tipo_contrato', models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo Completo'), ('MEDIO_TIEMPO', 'Medio Tiempo'), ('POR_HORAS', 'Por Horas'), ('PRACTICANTE', 'Practicante'), ('CONSULTOR', 'Consultor')], default='TIEMPO_COMPLETO', max_length=20, verbose_name='Tipo de Contrato')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('numero_empleado', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Empleado')),
                ('fecha_ultima_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Evaluación')),
                ('notas_laborales', models.TextField(blank=True, null=True, verbose_name='Notas Laborales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Convocatoria')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha de Cierre')),
                ('fecha_inicio_trabajo', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Trabajo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('MIXTA', 'Mixta')], default='EXTERNA', max_length=10, verbose_name='Tipo de Convocatoria')),
                ('requisitos_minimos', models.TextField(blank=True, null=True, verbose_name='Requisitos Mínimos')),
                ('requisitos_deseables', models.TextField(blank=True, null=True, verbose_name='Requisitos Deseables')),
                ('experiencia_minima', models.PositiveIntegerField(default=0, verbose_name='Experiencia Mínima (años)')),
                ('numero_vacantes', models.PositiveIntegerField(default=1, verbose_name='Número de Vacantes')),
                ('salario_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Ofrecido')),
                ('modalidad_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad de Trabajo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('responsable_rrhh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de RRHH')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('CURSO', 'Curso'), ('DIPLOMADO', 'Diplomado'), ('CERTIFICACION', 'Certificación'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TALLER', 'Taller'), ('SEMINARIO', 'Seminario'), ('CONGRESO', 'Congreso'), ('CONFERENCIA', 'Conferencia')], max_length=20, verbose_name='Tipo de Estudio')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('horas_lectivas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas Lectivas')),
                ('nivel', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('EXPERTO', 'Experto')], max_length=15, null=True, verbose_name='Nivel')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Curso de Especialización',
                'verbose_name_plural': 'Cursos de Especialización',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_profesional', models.TextField(blank=True, null=True, verbose_name='Resumen Profesional')),
                ('objetivo_profesional', models.TextField(blank=True, null=True, verbose_name='Objetivo Profesional')),
                ('telefono_profesional', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Teléfono Profesional')),
                ('email_profesional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Profesional')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Portfolio/Website')),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Archivo CV')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_experiencia', models.CharField(choices=[('GENERAL', 'General'), ('ESPECIFICA', 'Específica'), ('LIDERAZGO', 'Liderazgo'), ('TECNICA', 'Técnica'), ('ADMINISTRATIVA', 'Administrativa'), ('VENTAS', 'Ventas'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('INVESTIGACION', 'Investigación'), ('DOCENCIA', 'Docencia')], max_length=20, verbose_name='Tipo de Experiencia')),
                ('tipo_entidad', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('ONG', 'ONG'), ('INTERNACIONAL', 'Internacional'), ('MIXTO', 'Mixto')], max_length=15, verbose_name='Tipo de Entidad')),
                ('nombre_entidad', models.CharField(max_length=200, verbose_name='Nombre de la Entidad')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('motivo_salida', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Salida')),
                ('logros', models.TextField(blank=True, null=True, verbose_name='Logros Principales')),
                ('responsabilidades', models.TextField(blank=True, null=True, verbose_name='Responsabilidades')),
                ('supervisor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Supervisor')),
                ('telefono_referencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('TECNICO_SUPERIOR', 'Técnico Superior'), ('LICENCIADO', 'Licenciado'), ('INGENIERO', 'Ingeniero'), ('MAESTRO', 'Maestro'), ('DOCTOR', 'Doctor'), ('POSTGRADO', 'Postgrado'), ('DIPLOMADO', 'Diplomado'), ('CERTIFICACION', 'Certificación')], max_length=30, verbose_name='Grado')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('centro_estudio', models.CharField(max_length=200, verbose_name='Centro de Estudio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Formaciones Académicas',
                'ordering': ['-fecha_expedicion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener entre 8 y 11 dígitos', regex='^[0-9]{8,11}$')], verbose_name='Número de Documento')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de celular inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Postulación')),
                ('estado_postulacion', models.CharField(choices=[('POSTULADO', 'Postulado'), ('EN_REVISION', 'En Revisión'), ('ENTREVISTA', 'En Entrevista'), ('EVALUACION', 'En Evaluación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RETIRADO', 'Retirado')], default='POSTULADO', max_length=20, verbose_name='Estado de Postulación')),
                ('experiencia_anios', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('nivel_educacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de Educación')),
                ('institucion_educacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de Educación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='master.convocatoria', verbose_name='Convocatoria')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='master.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['numero_documento'], name='master_pers_numero__3c49c2_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='master_pers_email_5853cd_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['fecha_creacion'], name='master_pers_fecha_c_8ec37d_idx'),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='cv',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='master.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_especializacion', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='master.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='master.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='master.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='master.colaborador', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='master.area', verbose_name='Área'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado_postulacion'], name='master_post_estado__1b1c20_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['fecha_postulacion'], name='master_post_fecha_p_9e599b_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['persona', 'convocatoria'], name='master_post_persona_c3e838_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('persona', 'convocatoria')},
        ),
        migrations.AddIndex(
            model_name='formacionacademica',
            index=models.Index(fields=['cv'], name='master_form_cv_id_4f4989_idx'),
        ),
        migrations.AddIndex(
            model_name='formacionacademica',
            index=models.Index(fields=['grado'], name='master_form_grado_9df1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencialaboral',
            index=models.Index(fields=['cv'], name='master_expe_cv_id_4e93cf_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencialaboral',
            index=models.Index(fields=['tipo_experiencia'], name='master_expe_tipo_ex_1752b7_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencialaboral',
            index=models.Index(fields=['fecha_inicio'], name='master_expe_fecha_i_1a00a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['persona'], name='master_cv_persona_90c3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['fecha_actualizacion'], name='master_cv_fecha_a_a9d529_idx'),
        ),
        migrations.AddIndex(
            model_name='cursoespecializacion',
            index=models.Index(fields=['cv'], name='master_curs_cv_id_30dd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='cursoespecializacion',
            index=models.Index(fields=['tipo_estudio'], name='master_curs_tipo_es_55b82b_idx'),
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['estado'], name='master_conv_estado_3db3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['cargo'], name='master_conv_cargo_i_cca6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['fecha_apertura', 'fecha_cierre'], name='master_conv_fecha_a_cef31f_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['estado_laboral'], name='master_cola_estado__b6b22d_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['fecha_ingreso'], name='master_cola_fecha_i_f46a61_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['cargo'], name='master_cola_cargo_i_d5902a_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['numero_empleado'], name='master_cola_numero__d76d3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('area', 'nombre')},
        ),
    ]
