# Generated by Django 4.2.7 on 2025-09-14 21:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel')),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Mínimo')),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Máximo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='master.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Convocatoria')),
                ('descripcion', models.TextField(verbose_name='Descripción del Puesto')),
                ('fecha_apertura', models.DateTimeField(verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha de Cierre')),
                ('fecha_inicio_trabajo', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Trabajo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('MIXTA', 'Mixta')], default='EXTERNA', max_length=10, verbose_name='Tipo de Convocatoria')),
                ('requisitos_minimos', models.TextField(blank=True, null=True, verbose_name='Requisitos Mínimos')),
                ('requisitos_deseables', models.TextField(blank=True, null=True, verbose_name='Requisitos Deseables')),
                ('experiencia_minima', models.PositiveIntegerField(default=0, verbose_name='Experiencia Mínima (años)')),
                ('numero_vacantes', models.PositiveIntegerField(default=1, verbose_name='Número de Vacantes')),
                ('salario_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Ofrecido')),
                ('modalidad_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad de Trabajo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('responsable_rrhh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de RRHH')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='master.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener entre 8 y 11 dígitos', regex='^[0-9]{8,11}$')], verbose_name='Número de Documento')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de celular inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('estado_laboral', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('VACACIONES', 'En Vacaciones'), ('LICENCIA', 'En Licencia'), ('RENUNCIADO', 'Renunciado'), ('DESPEDIDO', 'Despedido')], default='ACTIVO', max_length=20, verbose_name='Estado Laboral')),
                ('tipo_contrato', models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo Completo'), ('MEDIO_TIEMPO', 'Medio Tiempo'), ('POR_HORAS', 'Por Horas'), ('PRACTICANTE', 'Practicante'), ('CONSULTOR', 'Consultor')], default='TIEMPO_COMPLETO', max_length=20, verbose_name='Tipo de Contrato')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('numero_empleado', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Empleado')),
                ('fecha_ultima_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Evaluación')),
                ('notas_laborales', models.TextField(blank=True, null=True, verbose_name='Notas Laborales')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='master.cargo', verbose_name='Cargo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='master.colaborador', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['-fecha_ingreso', 'apellido_paterno', 'apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener entre 8 y 11 dígitos', regex='^[0-9]{8,11}$')], verbose_name='Número de Documento')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de celular inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Postulación')),
                ('estado_postulacion', models.CharField(choices=[('POSTULADO', 'Postulado'), ('EN_REVISION', 'En Revisión'), ('ENTREVISTA', 'En Entrevista'), ('EVALUACION', 'En Evaluación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RETIRADO', 'Retirado')], default='POSTULADO', max_length=20, verbose_name='Estado de Postulación')),
                ('experiencia_anios', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('nivel_educacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel de Educación')),
                ('institucion_educacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución Educativa')),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cvs/aspirantes/', verbose_name='Archivo CV')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspirantes', to='master.convocatoria', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
                'ordering': ['-fecha_postulacion', 'apellido_paterno', 'apellido_materno'],
            },
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['estado'], name='master_conv_estado_3db3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['cargo'], name='master_conv_cargo_i_cca6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='convocatoria',
            index=models.Index(fields=['fecha_apertura', 'fecha_cierre'], name='master_conv_fecha_a_cef31f_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['estado_laboral'], name='master_cola_estado__b6b22d_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['fecha_ingreso'], name='master_cola_fecha_i_f46a61_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['cargo'], name='master_cola_cargo_i_d5902a_idx'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['numero_empleado'], name='master_cola_numero__d76d3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('area', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['estado_postulacion'], name='master_aspi_estado__85e053_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['fecha_postulacion'], name='master_aspi_fecha_p_0197c7_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['convocatoria'], name='master_aspi_convoca_d0b842_idx'),
        ),
    ]
