# Generated by Django 4.2.7 on 2025-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='nombre_empresa_externa',
            field=models.CharField(blank=True, help_text='Nombre de la empresa externa para convocatorias de tipo Externa o Mixta', max_length=200, null=True, verbose_name='Nombre de la Empresa Externa'),
        ),
    ]
