# Generated by Django 4.2.7 on 2025-09-14 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Postulación')),
                ('estado_postulacion', models.CharField(choices=[('POSTULADO', 'Postulado'), ('EN_REVISION', 'En Revisión'), ('ENTREVISTA', 'En Entrevista'), ('EVALUACION', 'En Evaluación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('RETIRADO', 'Retirado')], default='POSTULADO', max_length=20, verbose_name='Estado de Postulación')),
                ('experiencia_anios', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('nivel_educacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de Educación')),
                ('institucion_educacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de Educación')),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Archivo CV')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='aspirante',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'], 'verbose_name': 'Aspirante', 'verbose_name_plural': 'Aspirantes'},
        ),
        migrations.RemoveIndex(
            model_name='aspirante',
            name='master_aspi_estado__85e053_idx',
        ),
        migrations.RemoveIndex(
            model_name='aspirante',
            name='master_aspi_fecha_p_0197c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='aspirante',
            name='master_aspi_convoca_d0b842_idx',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='convocatoria',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='cv_archivo',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='estado_postulacion',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='experiencia_anios',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='fecha_postulacion',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='institucion_educacion',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='nivel_educacion',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['activo'], name='master_aspi_activo_ee1218_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['fecha_registro'], name='master_aspi_fecha_r_ee128d_idx'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='aspirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='master.aspirante', verbose_name='Aspirante'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='master.convocatoria', verbose_name='Convocatoria'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado_postulacion'], name='master_post_estado__1b1c20_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['fecha_postulacion'], name='master_post_fecha_p_9e599b_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['aspirante', 'convocatoria'], name='master_post_aspiran_6b7222_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('aspirante', 'convocatoria')},
        ),
    ]
