# Generated by Django 4.2.7 on 2025-09-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_restructure_aspirante_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('TECNICO_SUPERIOR', 'Técnico Superior'), ('LICENCIADO', 'Licenciado'), ('INGENIERO', 'Ingeniero'), ('MAESTRO', 'Maestro'), ('DOCTOR', 'Doctor'), ('POSTGRADO', 'Postgrado'), ('DIPLOMADO', 'Diplomado'), ('CERTIFICACION', 'Certificación')], max_length=30, verbose_name='Grado')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('centro_estudio', models.CharField(max_length=200, verbose_name='Centro de Estudio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='master.aspirante', verbose_name='Aspirante')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='master.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Formaciones Académicas',
                'ordering': ['-fecha_expedicion'],
                'indexes': [models.Index(fields=['aspirante'], name='master_form_aspiran_0832fa_idx'), models.Index(fields=['colaborador'], name='master_form_colabor_70c2fe_idx'), models.Index(fields=['grado'], name='master_form_grado_9df1cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_experiencia', models.CharField(choices=[('GENERAL', 'General'), ('ESPECIFICA', 'Específica'), ('LIDERAZGO', 'Liderazgo'), ('TECNICA', 'Técnica'), ('ADMINISTRATIVA', 'Administrativa'), ('VENTAS', 'Ventas'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('INVESTIGACION', 'Investigación'), ('DOCENCIA', 'Docencia')], max_length=20, verbose_name='Tipo de Experiencia')),
                ('tipo_entidad', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('ONG', 'ONG'), ('INTERNACIONAL', 'Internacional'), ('MIXTO', 'Mixto')], max_length=15, verbose_name='Tipo de Entidad')),
                ('nombre_entidad', models.CharField(max_length=200, verbose_name='Nombre de la Entidad')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('motivo_salida', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Salida')),
                ('logros', models.TextField(blank=True, null=True, verbose_name='Logros Principales')),
                ('responsabilidades', models.TextField(blank=True, null=True, verbose_name='Responsabilidades')),
                ('supervisor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Supervisor')),
                ('telefono_referencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='master.aspirante', verbose_name='Aspirante')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='master.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['aspirante'], name='master_expe_aspiran_ba3684_idx'), models.Index(fields=['colaborador'], name='master_expe_colabor_51a800_idx'), models.Index(fields=['tipo_experiencia'], name='master_expe_tipo_ex_1752b7_idx'), models.Index(fields=['fecha_inicio'], name='master_expe_fecha_i_1a00a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudio', models.CharField(choices=[('CURSO', 'Curso'), ('DIPLOMADO', 'Diplomado'), ('CERTIFICACION', 'Certificación'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('TALLER', 'Taller'), ('SEMINARIO', 'Seminario'), ('CONGRESO', 'Congreso'), ('CONFERENCIA', 'Conferencia')], max_length=20, verbose_name='Tipo de Estudio')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('horas_lectivas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas Lectivas')),
                ('nivel', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('EXPERTO', 'Experto')], max_length=15, null=True, verbose_name='Nivel')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_especializacion', to='master.aspirante', verbose_name='Aspirante')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_especializacion', to='master.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Curso de Especialización',
                'verbose_name_plural': 'Cursos de Especialización',
                'ordering': ['-fecha_fin'],
                'indexes': [models.Index(fields=['aspirante'], name='master_curs_aspiran_0beca9_idx'), models.Index(fields=['colaborador'], name='master_curs_colabor_f2e850_idx'), models.Index(fields=['tipo_estudio'], name='master_curs_tipo_es_55b82b_idx')],
            },
        ),
    ]
