# Generated by Django 4.2.7 on 2025-09-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_convocatoria_nombre_empresa_externa'),
    ]

    operations = [
    ]
