# Generated by Django 4.2.7 on 2025-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20250924_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='motivo_salida',
            field=models.CharField(blank=True, choices=[('RENUNCIA', 'Renuncia'), ('DESPIDO', 'Despido'), ('CONTRATO_VENCIDO', 'Contrato Vencido'), ('TERMINO_PROYECTO', 'Término de Proyecto'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Motivo de Salida'),
        ),
    ]
