# Generated by Django 4.2.7 on 2025-09-17 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_formacionacademica_experiencialaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_profesional', models.TextField(blank=True, null=True, verbose_name='Resumen Profesional')),
                ('objetivo_profesional', models.TextField(blank=True, null=True, verbose_name='Objetivo Profesional')),
                ('telefono_profesional', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Teléfono Profesional')),
                ('email_profesional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Profesional')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Portfolio/Website')),
                ('cv_archivo', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Archivo CV')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('RUC', 'RUC')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener entre 8 y 11 dígitos', regex='^[0-9]{8,11}$')], verbose_name='Número de Documento')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)'), ('CONVIVIENTE', 'Conviviente')], max_length=20, verbose_name='Estado Civil')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de celular inválido', regex='^[0-9+\\-\\s()]{7,15}$')], verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.RemoveIndex(
            model_name='cursoespecializacion',
            name='master_curs_aspiran_0beca9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cursoespecializacion',
            name='master_curs_colabor_f2e850_idx',
        ),
        migrations.RemoveIndex(
            model_name='experiencialaboral',
            name='master_expe_aspiran_ba3684_idx',
        ),
        migrations.RemoveIndex(
            model_name='experiencialaboral',
            name='master_expe_colabor_51a800_idx',
        ),
        migrations.RemoveIndex(
            model_name='formacionacademica',
            name='master_form_aspiran_0832fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='formacionacademica',
            name='master_form_colabor_70c2fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='postulacion',
            name='master_post_aspiran_6b7222_idx',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='cursoespecializacion',
            name='aspirante',
        ),
        migrations.RemoveField(
            model_name='cursoespecializacion',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='aspirante',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='formacionacademica',
            name='aspirante',
        ),
        migrations.RemoveField(
            model_name='formacionacademica',
            name='colaborador',
        ),
        migrations.AddIndex(
            model_name='cursoespecializacion',
            index=models.Index(fields=['cv'], name='master_curs_cv_id_30dd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencialaboral',
            index=models.Index(fields=['cv'], name='master_expe_cv_id_4e93cf_idx'),
        ),
        migrations.AddIndex(
            model_name='formacionacademica',
            index=models.Index(fields=['cv'], name='master_form_cv_id_4f4989_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['persona', 'convocatoria'], name='master_post_persona_c3e838_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['numero_documento'], name='master_pers_numero__3c49c2_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='master_pers_email_5853cd_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['fecha_creacion'], name='master_pers_fecha_c_8ec37d_idx'),
        ),
        migrations.AddField(
            model_name='cv',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='master.persona', verbose_name='Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='master.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_especializacion', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='master.cv', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='master.persona', verbose_name='Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('persona', 'convocatoria')},
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['persona'], name='master_cv_persona_90c3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cv',
            index=models.Index(fields=['fecha_actualizacion'], name='master_cv_fecha_a_a9d529_idx'),
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='aspirante',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='cv_archivo',
        ),
        migrations.DeleteModel(
            name='Aspirante',
        ),
    ]
